### ISSUE TITLE
Restrictive upper bounds on transformers and bifunctors

### ISSUE THREAD

**Issue by grayjay** [edsko/tracetree#1]
I wasn't able to build tracetree with GHC 8.0.1 because it requires transformers < 0.5, and transformers < 0.5 requires base < 4.9.  The build succeeded when I lifted the upper bound on transformers.

**Comment by edsko** [comment]
Thanks for the report! Fixed in github and edited the .cabal file on Hackage.

**Comment by grayjay** [comment]
Thanks!
